### ISSUE TITLE
There are some problems when using it

### ISSUE THREAD

**Issue by 1070057723liu** [salesforce/kubelet-summary-exporter#3]
After I deploy in K8S as required, and after executing Kubectl -n Kubelet-summary-Exporter Port-forward Ds/Kubelet-summary-Exporter 9091 ，Curl localhost:9091/metrics, which returns nothing and a status code of 200.

**Comment by karlhungus** [comment]
I've found the docker daemon to be particularly slow responding to node data (hence the long timeout https://github.com/salesforce/kubelet-summary-exporter/blob/bb5a8611efea5b5d135298390cf1c4cf5b8649fb/config/local/patch-daemonset.yaml#L15), so it might be worth curling the metrics endpoint a few times.

Is there any output from skaffold or from the pod `kubectl -nkubelet-summary-exporter logs ds/kubelet-summary-exporter`

It should look like this:
```
❯ kubectl -nkubelet-summary-exporter logs ds/kubelet-summary-exporter
{"level":"warn","caller":"utils/utils.go:34","message":"using insecure tls","app":"kubelet-stats-exporter"}
{"level":"info","caller":"kubelet-summary-exporter/main.go:68","message":"using updated serverAddr for certificate validation","app":"kubelet-stats-exporter","hostname":"docker-desktop","original":"docker-desktop"}
```

You should get output from port forwarding like this:
```
❯ kubectl -nkubelet-summary-exporter port-forward ds/kubelet-summary-exporter 9091
Forwarding from 127.0.0.1:9091 -> 9091
Forwarding from [::1]:9091 -> 9091
Handling connection for 9091
```

Output from metrics endpout should look like

```
➜ curl localhost:9091/metrics
# HELP kube_pod_ephemeral_storage_used_bytes Ephemeral storage used in bytes
# TYPE kube_pod_ephemeral_storage_used_bytes gauge
kube_pod_ephemeral_storage_used_bytes{namespace="kube-system",node="docker-desktop",pod="coredns-95db45d46-9xpkd"} 16384
kube_pod_ephemeral_storage_used_bytes{namespace="kube-system",node="docker-desktop",pod="coredns-95db45d46-lgwcv"} 16384
kube_pod_ephemeral_storage_used_bytes{namespace="kube-system",node="docker-desktop",pod="etcd-docker-desktop"} 4096
kube_pod_ephemeral_storage_used_bytes{namespace="kube-system",node="docker-desktop",pod="kube-apiserver-docker-desktop"} 4096
kube_pod_ephemeral_storage_used_bytes{namespace="kube-system",node="docker-desktop",pod="kube-controller-manager-docker-desktop"} 4096
kube_pod_ephemeral_storage_used_bytes{namespace="kube-system",node="docker-desktop",pod="kube-proxy-rw8zf"} 20660
kube_pod_ephemeral_storage_used_bytes{namespace="kube-system",node="docker-desktop",pod="kube-scheduler-docker-desktop"} 4096
kube_pod_ephemeral_storage_used_bytes{namespace="kube-system",node="docker-desktop",pod="storage-provisioner"} 4096
kube_pod_ephemeral_storage_used_bytes{namespace="kube-system",node="docker-desktop",pod="vpnkit-controller"} 4096
kube_pod_ephemeral_storage_used_bytes{namespace="kubelet-summary-exporter",node="docker-desktop",pod="kubelet-summary-exporter-qljmd"} 4096

```


If you could provide information about your local environment I may be able to help a bit more

**Comment by 1070057723liu** [comment]
the logs and the output from port forwarding are same as yours, but Output from metrics endpout is nothing. And I deployed it on some cloud server

>curl -v localhost:9091/metrics
* About to connect() to localhost port 9091 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 9091 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9091
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Date: Wed, 28 Sep 2022 01:54:17 GMT
< Content-Length: 0

**Comment by karlhungus** [comment]
>And I deployed it on some cloud server

Unfortunatly this dosn't give me enough to go on -- try it locally with docker for desktop (because i know their kubelet responds to stats/summary). Alternatly attempt to curl your kubelets /stats/summary endpoint either via api i.e.

```
$ kubectl proxy
```

```
$ curl localhost:8001/api/v1/nodes/<nodename>/proxy/stats/summary
```

Or by a local pod curling `:10250/stats/summary` .

This issue did point out a logging miss though, i'll pr up a fix for that shortly.

**Comment by 1070057723liu** [comment]
Your suggestion is very useful.Thank u very much.

**Comment by karlhungus** [comment]
Happy to help! The lastest build should log an error in your case, would be nice to dump that here for othere who encounter the same issue.
